### ISSUE TITLE
cover picture for stories is not showing

### ISSUE THREAD

**Issue by AlekseiNovoselov** [inappstory/android-sdk#4]
<img width="250" alt="empty_custom_list_items" src="https://user-images.githubusercontent.com/8673877/159533290-a2502638-051b-4032-b75e-3cd354b75b58.jpeg">

version: 1.6.1 
photo is from https://github.com/inappstory/Android-Example for CUSTOM LIST

**Comment by paperrose** [comment]
Greetings, Alexey!
Thank you for your report!

According to screenshot you use old version of examples.
Between versions 1.5 and 1.6 there is some usage changes. Here is a link to migrations:
https://github.com/inappstory/android-sdk/blob/main/docs/Migrations.md#from-15x-to-16x

We updated main branch for examples repository.
Can you check the latest version of examples?

**Comment by AlekseiNovoselov** [comment]
it works with latest version in Android-Example:

after migration from 1.5 to 1.6 implementation of `showImage()` in `IStoriesListItem` should have been updated from:
```kotlin
    override fun setImage(itemView: View, url: String?, backgroundColor: Int) {
        val imageView = itemView.findViewById<ImageView>(R.id.in_app_story_image_view)
        if (!url.isNullOrBlank()) {
            val cache = InAppStoryService.getInstance().fastCache
            ImageLoader.getInstance().displayImage(url, -1, imageView, cache)
        } else {
            imageView.setBackgroundColor(backgroundColor)
        }
    }
```
to:
```kotlin
    override fun setImage(itemView: View, url: String?, backgroundColor: Int) {
        val imageView = itemView.findViewById<ImageView>(R.id.in_app_story_image_view)
        if (url != null && !url.isEmpty()) {
            ImageLoader.getInstance().displayImage(url, -1, imageView)
        } else {
            imageView.setBackgroundColor(backgroundColor)
        }
    }
```

thanks for your answer
